### ISSUE TITLE
Improvements for next version

### ISSUE THREAD

**Issue by matthijskooijman** [meetjestad/mjs_pcb#1]
- [x] Add solder jumpers to I2C breakout
- [x] Easier way to reset board (header with GND and RESET)
- [x] Change value of C2 and C4 to 100uF
- [x] Add top groundplane under SX and antenna
- [x] Disconnect AREF from VCC
- [ ] ~~Add capacitor on AREF?~~
- [ ] ~~Expose VIN (input to regulator) on experiment area? Does have a small risk of over-voltage on components on accidental short-circuit.~~
- [x] Slightly move serial connector to improve silkscreen readability?

Capacitor on AREF is not essential, but 100nF is recommended for ADC stability. It seems there is some room next to C1 (if you make C1 the AREF capacitor and add a new one for VCC between C1 and U3, moving U3 a bit).

Exposing the reset pin on a header seems tricky in the layout. This could be a normal 2.54mm jumper header to reset using a jumper or other stuff (keys). Or just pads, a bit closer together, so you can reset using keys or similar tools without having to solder on pins? Might not be entirely reliable, with pins is probably easier. It seems there is some room in the top right, next to the power jumper to put a reset jumper, routing the RESET line on the top between pin 1 and 2 of the power jumper.

**Comment by giplt** [comment]
- [x] Add solder jumpers to I2C breakout
- [x] Change value of C2 and C4 to 100uF
- [x] Disconnect AREF from VCC
- [ ] Add top groundplane under SX and antenna
- [ ] Slightly move serial connector to improve silkscreen readability?
- [ ] Easier way to reset board (header with GND and RESET)
- [ ] Expose VIN (input to regulator) on experiment area? Does have a small risk of over-voltage on components on accidental short-circuit.
